variables:
  PYPI_USER: SECURE
  PYPI_PASSWORD: SECURE

stages:
  - test
  - build
  - deploy

.poetry:
  before_script:
    # Install and configure poetry
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
    - poetry config repositories.sdsrocks ${STYRIA_EXTRA_INDEX_URL}/simple
    # Install dependencies
    - poetry install

.test:
  stage: test
  extends: .poetry
  script:
    - poetry run pytest

Python3.6:
  extends: .test
  image: python:3.6

Python3.7:
  extends: .test
  image: python:3.7

Python3.8:
  extends: .test
  image: python:3.8
  
test_build:
  extends: .poetry
  stage: build
  image: python:3.7
  script:
    - poetry build

deploy:
  stage: deploy
  image: python:3.7
  # before_script:
  #   - pip install twine>=1.12.1
  # script:
  #   - python setup.py sdist bdist_wheel
  #   - twine upload --repository-url $TWINE_REPOSITORY_URL dist/*
  # only:
  #   - tags
  extends: .poetry
  script:
    - poetry publish --build

