variables:
  PYPI_USER: SECURE
  PYPI_PASSWORD: SECURE

stages:
  - test
  - build
  - deploy

.cleanup_pypirc: &cleanup_pypirc |
  rm -vf ~/.pypirc

.test:
  stage: test
  before_script:
    # # adding pip cache
    # - export PIP_CACHE_DIR="/home/gitlabci/cache/pip-cache"
    # # install dependencies
    # - pip install --extra-index-url="${STYRIA_EXTRA_INDEX_URL}/simple" --trusted-host="pypi.sds.rocks" -e .[test]
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    poetry config repositories.sdsrocks ${STYRIA_EXTRA_INDEX_URL}/simple
    poetry install
  script:
    - poetry run pytest
  after_script:
    - *cleanup_pypirc

Python3.6:
  extends: .test
  image: python:3.6

Python3.7:
  extends: .test
  image: python:3.7

Python3.8:
  extends: .test
  image: python:3.8
  
test_build:
  stage: build
  image: python:3.7
  script:
    - python setup.py build
    - python setup.py install
  after_script:
    - *cleanup_pypirc

deploy:
  stage: deploy
  image: python:3.7
  before_script:
    - pip install twine>=1.12.1
  script:
    - python setup.py sdist bdist_wheel
    - twine upload --repository-url $TWINE_REPOSITORY_URL dist/*
  only:
    - tags
  after_script: 
    - *cleanup_pypirc


