name: Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
        
  test_build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Test build
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry build
      if: startsWith(github.event.ref, 'refs/tags')
        run: |
          poetry config repositories.sddrocks http://pypi.sds.rocks:9090
          poetry publish --build -r sddrocks -u ${{secrets.TWINE_USERNAME}} -p ${{secrets.TWINE_PASSWORD}}
