name: Publish Confgetti to PyPI

on:
  push:
    tags:
    - '*.*.*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Deploy to PyPI
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config pypi-token.pypi ${{secrets.POETRY_PYPI_TOKEN}}
        poetry publish --build
