name: Publish Confgetti to PyPI

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Deploy to PyPI
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry publish --build -r sddrocks -u ${{secrets.TWINE_USERNAME}} -p ${{secrets.TWINE_PASSWORD}}
